export const SET_FILTER_DATA = "SET_FILTER_DATA";
export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const SET_YEARLY_MOVIE_DATA = "SET_YEARLY_MOVIE_DATA";
