import { MovieData } from "../types";

export const result: MovieData[] = [
  {
    adult: false,
    backdrop_path: "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
    genre_ids: [18, 878, 28],
    id: 695721,
    original_language: "en",
    original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    overview:
      "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
    popularity: 3233.513,
    poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
    release_date: "2023-11-15",
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    video: false,
    vote_average: 7.2,
    vote_count: 1009,
  },
  {
    adult: false,
    backdrop_path: "/bckxSN9ueOgm0gJpVJmPQrecWul.jpg",
    genre_ids: [28, 12, 14],
    id: 572802,
    original_language: "en",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1999.169,
    poster_path: "/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
    release_date: "2023-12-20",
    title: "Aquaman and the Lost Kingdom",
    video: false,
    vote_average: 6.6,
    vote_count: 171,
  },
  {
    adult: false,
    backdrop_path: "/15Fe18IglCCP1jJoj5F529on0IA.jpg",
    genre_ids: [28, 35],
    id: 1029575,
    original_language: "en",
    original_title: "The Family Plan",
    overview:
      "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
    popularity: 1564.216,
    poster_path: "/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg",
    release_date: "2023-12-14",
    title: "The Family Plan",
    video: false,
    vote_average: 7.5,
    vote_count: 341,
  },
  {
    adult: false,
    backdrop_path: "/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg",
    genre_ids: [28, 80],
    id: 891699,
    original_language: "en",
    original_title: "Silent Night",
    overview:
      "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
    popularity: 1329.943,
    poster_path: "/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg",
    release_date: "2023-11-30",
    title: "Silent Night",
    video: false,
    vote_average: 5.9,
    vote_count: 125,
  },
  {
    adult: false,
    backdrop_path: "/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 1102.163,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.2,
    vote_count: 523,
  },
  {
    adult: false,
    backdrop_path: "/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg",
    genre_ids: [27, 53, 9648],
    id: 1071215,
    original_language: "en",
    original_title: "Thanksgiving",
    overview:
      "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.",
    popularity: 1126.478,
    poster_path: "/mJaqjYcQ1CclhHmO6Z3iMIGUP0Y.jpg",
    release_date: "2023-11-16",
    title: "Thanksgiving",
    video: false,
    vote_average: 6.7,
    vote_count: 264,
  },
  {
    adult: false,
    backdrop_path: "/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 520758,
    original_language: "en",
    original_title: "Chicken Run: Dawn of the Nugget",
    overview:
      "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
    popularity: 844.013,
    poster_path: "/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg",
    release_date: "2023-12-08",
    title: "Chicken Run: Dawn of the Nugget",
    video: false,
    vote_average: 7.6,
    vote_count: 265,
  },
  {
    adult: false,
    backdrop_path: "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
    genre_ids: [878, 28, 12],
    id: 848326,
    original_language: "en",
    original_title: "Rebel Moon - Part One: A Child of Fire",
    overview:
      "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
    popularity: 923.889,
    poster_path: "/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg",
    release_date: "2023-12-15",
    title: "Rebel Moon - Part One: A Child of Fire",
    video: false,
    vote_average: 6.4,
    vote_count: 409,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 752.689,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.1,
    vote_count: 5597,
  },
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
    popularity: 740.775,
    poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
    release_date: "2023-01-05",
    title: "Freelance",
    video: false,
    vote_average: 6.5,
    vote_count: 367,
  },
  {
    adult: false,
    backdrop_path: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    genre_ids: [80, 18, 36],
    id: 466420,
    original_language: "en",
    original_title: "Killers of the Flower Moon",
    overview:
      "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
    popularity: 770.179,
    poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    release_date: "2023-10-18",
    title: "Killers of the Flower Moon",
    video: false,
    vote_average: 7.6,
    vote_count: 1575,
  },
  {
    adult: false,
    backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 647.433,
    poster_path: "/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
    release_date: "2023-10-12",
    title: "Trolls Band Together",
    video: false,
    vote_average: 7.1,
    vote_count: 411,
  },
  {
    adult: false,
    backdrop_path: "/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg",
    genre_ids: [16, 35, 10751],
    id: 1075794,
    original_language: "en",
    original_title: "Leo",
    overview:
      "Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.",
    popularity: 574.856,
    poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    release_date: "2023-11-17",
    title: "Leo",
    video: false,
    vote_average: 7.6,
    vote_count: 654,
  },
  {
    adult: false,
    backdrop_path: "/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
    genre_ids: [27, 9648],
    id: 507089,
    original_language: "en",
    original_title: "Five Nights at Freddy's",
    overview:
      "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
    popularity: 580.153,
    poster_path: "/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
    release_date: "2023-10-25",
    title: "Five Nights at Freddy's",
    video: false,
    vote_average: 7.8,
    vote_count: 2936,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 637.714,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.2,
    vote_count: 4527,
  },
  {
    adult: false,
    backdrop_path: "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
    genre_ids: [28, 12, 18],
    id: 670292,
    original_language: "en",
    original_title: "The Creator",
    overview:
      "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
    popularity: 660.289,
    poster_path: "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
    release_date: "2023-09-27",
    title: "The Creator",
    video: false,
    vote_average: 7.1,
    vote_count: 1568,
  },
  {
    adult: false,
    backdrop_path: "/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg",
    genre_ids: [18, 9648, 53, 878],
    id: 726209,
    original_language: "en",
    original_title: "Leave the World Behind",
    overview:
      "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
    popularity: 504.757,
    poster_path: "/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
    release_date: "2023-11-22",
    title: "Leave the World Behind",
    video: false,
    vote_average: 6.6,
    vote_count: 1089,
  },
  {
    adult: false,
    backdrop_path: "/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg",
    genre_ids: [28, 12, 53],
    id: 299054,
    original_language: "en",
    original_title: "Expend4bles",
    overview:
      "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
    popularity: 540.75,
    poster_path: "/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
    release_date: "2023-09-15",
    title: "Expend4bles",
    video: false,
    vote_average: 6.4,
    vote_count: 921,
  },
  {
    adult: false,
    backdrop_path: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
    genre_ids: [35, 12, 14],
    id: 346698,
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    popularity: 419.27,
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    release_date: "2023-07-19",
    title: "Barbie",
    video: false,
    vote_average: 7.2,
    vote_count: 6453,
  },
  {
    adult: false,
    backdrop_path: "/ipmUfBf3RxIdATbYI4CcPlnTsWs.jpg",
    genre_ids: [18, 35, 53],
    id: 930564,
    original_language: "en",
    original_title: "Saltburn",
    overview:
      "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton, who invites him to Saltburn, his eccentric family's sprawling estate, for a summer never to be forgotten.",
    popularity: 375.845,
    poster_path: "/qjhahNLSZ705B5JP92YMEYPocPz.jpg",
    release_date: "2023-11-16",
    title: "Saltburn",
    video: false,
    vote_average: 7.2,
    vote_count: 184,
  },
];
